### ISSUE TITLE
[ERROR] Opam has not been initialised, please run `opam init'

### ISSUE THREAD

**Issue by k33g** [dylibso/wasmstore#14]
I tried:
```bash
docker pull dylibso/wasmstore
docker run --rm -it -p 6384:6384 dylibso/wasmstore
```

I got this error:
```bash
[ERROR] Opam has not been initialised, please run `opam init'
```

I get the same error with the following:
```bash
git clone https://github.com/dylibso/wasmstore.git
cd wasmstore
docker build -t wasmstore .
docker run -it -p 6384:6384 wasmstore
```

> system: `x86_64 GNU/Linux`

**Comment by zshipko** [comment]
Thanks! I get the same error with `dylibso/wasmstore` but from the local repo I was able to run it:

```
$ docker build --no-cache -t wasmstore .
[+] Building 235.5s (27/27) FINISHED
$ docker run -it -p 6384:6384 wasmstore
[application]: Starting server on 0.0.0.0:6384, cors=false, tls=false
```

I will try to figure out what's going on - but I thought Docker was supposed to fix the "it works on my machine" thing!

**Comment by zshipko** [comment]
I was able to replicate the issue on another machine and just pushed up a change that seems to fix it. I ended up switching the final image from `ocaml/opam` to `debian`.

The latest registry image will also be updated once https://github.com/dylibso/wasmstore/actions/runs/5771112672/job/15644776888 finishes running.

**Comment by k33g** [comment]
I tried the build again and got this when I ran: `docker run -it -p 6384:6384 wasmstore`
```
wasmstore: internal error, uncaught exception:
           Unix.Unix_error(Unix.EINVAL, "io_uring_queue_init", "")
```
And it is the same problem with the image from the Docker hub

I'm testing with an Intel VM (OrbStack) on a MacBook Pro M1. I don't have an intel machine on hand for about ten days, but I can try with Gitpod

**Comment by zshipko** [comment]
Ah interesting! I will have to take a look on an M1 machine. I should be able to test it out early in the week.

**Comment by k33g** [comment]
It works on Gitpod
<img width="806" alt="image" src="https://github.com/dylibso/wasmstore/assets/491848/6bf87475-71a6-437b-b680-bb7dbc152719">

so it's probably an issue with OrbStack

I think you can close this issue, I will test later on a real machine

**Comment by zshipko** [comment]
Ok, great! I will leave this open as a reminder to test it out myself.
